version: '3.8'
services:
  api:
    build:
      context: ./
      target: 'builder'
    container_name: rsapi
    # command: sh -c "cargo watch -x run"
    command: sh -c "cargo run"
    tty: true
    working_dir: '/src'
    volumes:
      - .:/src/:cached
    expose:
      - '8080'
    ports:
      - '8080:8000'
    depends_on:
      - db
  db:
    image: postgres:14.8
    container_name: psql_db
    restart: always
    environment:
      POSTGRES_DB: rustdb
      POSTGRES_USER: tkmk
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - '5432:5432'