name: Rust

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

# CHOOSE ENVIRONMENT
# env:
#   CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    environment: 
      name: dev

    steps:
    - uses: actions/checkout@v3
    - name: Build
      # USE ENVIRONMENT
      # env:
      #   DATABASE_URL: ${{ vars.DATABASE_URL  }}
      run: |
        cargo install sqlx-cli --no-default-features --features rustls,postgres
        cargo sqlx prepare
        SQLX_OFFLINE=true cargo build --verbose 
    - name: Run tests
      run: cargo test --verbose