name: Rust

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        environment: dev
        working_directory: ./
        DATABASE_URL: ${{ vars.DATABASE_URL  }}
    - name: Build
      run: |
        cargo install sqlx-cli
        cargo sqlx prepare
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose